### ISSUE TITLE
设置cookie里面“1&token=”是否可以写死？

### ISSUE THREAD

**Issue by TibbersForAnnieHastur** [jing332/xmly-downloader-qt5#1]
上面的比如：后面无法设置，cookie里面需要复制两段还得加个“=”
![微信图片_20200715143348](https://user-images.githubusercontent.com/56671524/87511661-3a1ce900-c6a8-11ea-95e5-81f8650313c1.png)

**Comment by jing332** [comment]
你是指编辑框上面的说明无法选择复制么？

**Comment by TibbersForAnnieHastur** [comment]
对的，示例无法复制，或者让人直接填1&_token里面的值，别让人填“1&_token=”+value了

**Comment by TibbersForAnnieHastur** [comment]
不过软件确实牛逼，乌拉！

**Comment by jing332** [comment]
谢谢夸奖啦😄
明天上午我就改下
