### ISSUE TITLE
完美运行，发个ISSUE感谢一下大佬，顺便交一下膝盖

### ISSUE THREAD

**Issue by grant-Gan** [jing332/xmly-downloader-qt5#5]

**Comment by grant-Gan** [comment]
对了, 一个小小的建议, 如果能够发布win/Linux/mac平台直接能用的执行文件的话, 感觉会更火 !

**Comment by jing332** [comment]
其实Github Actions里有编译好的Artifact啦

**Comment by jing332** [comment]
https://github.com/jing332/xmly-downloader-qt5/actions

**Comment by grant-Gan** [comment]
好吧, 感谢扫盲
