### ISSUE TITLE
Mac 版本无法运行

### ISSUE THREAD

**Issue by skykain** [jing332/xmly-downloader-qt5#8]
app 是下载坚果云上面的文件，应该是最新的版本
系统版本：macOS 10.15.6 

错误提示如下：
![gpusPv](https://cdn.jsdelivr.net/gh/skykain/imgStorge/uPic/gpusPv.png)

感觉构建出来的 app 应该是 32 位程序，所以 10.15.6 运行不了

自己试 Clone 下来静态编译，竟然完美运行了，很好的工具，希望作者能一直更新下去 👍🏻👍🏻👍🏻

**Comment by skykain** [comment]
是不是因为构建出来的 app 是32位程序，所以 10.15.6 不支持导致？之前的包是可以正常运行的···

**Comment by jing332** [comment]
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
这是Github Actions MacOS的构建环境，版本也是10.15。我没用过MacOS，具体什么原因也不知道了。
